function project_root = setup_ad_rann()
%SETUP_AD_RANN Initialize paths for the AD-RaNN project.
%
% Usage:
%   project_root = setup_ad_rann();
%
% This function adds:
%   1. project root
%   2. src and all its subfolders
%   3. example and all its subfolders
%   4. tests and all its subfolders
%
% It deliberately does not add:
%   data, docs, results
%
% This avoids accidentally calling old scripts or result files.

    %% ====================================================================
    %  Locate project root
    % =====================================================================

    this_file = mfilename('fullpath');

    if isempty(this_file)
        error('Unable to determine the location of setup_ad_rann.m.');
    end

    project_root = fileparts(this_file);

    %% ====================================================================
    %  Required project folders
    % =====================================================================

    src_dir = fullfile(project_root,'src');

    % Your current repository uses "example".
    % The second candidate supports a future rename to "examples".
    example_dir = fullfile(project_root,'example');

    if exist(example_dir,'dir') ~= 7
        example_dir = fullfile(project_root,'examples');
    end

    tests_dir = fullfile(project_root,'tests');

    %% ====================================================================
    %  Validate project structure
    % =====================================================================

    if exist(src_dir,'dir') ~= 7
        error('The src folder was not found:\n%s',src_dir);
    end

    if exist(example_dir,'dir') ~= 7
        error([ ...
            'Neither the example nor examples folder was found under:\n', ...
            '%s'],project_root);
    end

    %% ====================================================================
    %  Add paths
    % =====================================================================

    % Add project root so setup and root-level utilities are visible.
    addpath(project_root,'-begin');

    % Add source code recursively.
    addpath(genpath(src_dir),'-begin');

    % Add runnable examples recursively.
    addpath(genpath(example_dir),'-begin');

    % Add tests when available.
    if exist(tests_dir,'dir') == 7
        addpath(genpath(tests_dir),'-end');
    end

    %% ====================================================================
    %  Remove unwanted folders generated by genpath
    % =====================================================================

    remove_generated_folders(src_dir);
    remove_generated_folders(example_dir);

    if exist(tests_dir,'dir') == 7
        remove_generated_folders(tests_dir);
    end

    %% ====================================================================
    %  Report
    % =====================================================================

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('AD-RaNN project initialized\n');
    fprintf('============================================================\n');
    fprintf('Project root : %s\n',project_root);
    fprintf('Source       : %s\n',src_dir);
    fprintf('Examples     : %s\n',example_dir);

    if exist(tests_dir,'dir') == 7
        fprintf('Tests        : %s\n',tests_dir);
    end

    fprintf('============================================================\n\n');

end

function remove_generated_folders(parent_dir)
%REMOVE_GENERATED_FOLDERS Remove folders that should not remain on path.

    folder_names = { ...
        '.git', ...
        '.github', ...
        '.vscode', ...
        '__pycache__', ...
        'private', ...
        'results', ...
        'data'};

    for k = 1:numel(folder_names)

        folder_path = fullfile(parent_dir,folder_names{k});

        if exist(folder_path,'dir') == 7 && ...
                contains([path,pathsep],[folder_path,pathsep])

            rmpath(genpath(folder_path));
        end
    end

end