function u = evaluate_ac2d_trial( ...
    X,p,basis,coef_base,growth,coef_growth)
%EVALUATE_AC2D_TRIAL Evaluate a base or base+growth solution.

    base = ...
        evaluate_ac2d_base_state( ...
            X,p,basis,coef_base,0);

    u = base.u;

    if nargin < 5 || isempty(growth) || ...
       ~isstruct(growth) || ...
       ~isfield(growth,'active') || ...
       ~growth.active

        return;
    end

    frozen = ...
        evaluate_ac2d_base_state( ...
            X, ...
            growth.frozen_p, ...
            basis, ...
            growth.frozen_base_coef, ...
            2);

    G = ...
        evaluate_growth_features( ...
            X,growth.model,growth.rho,frozen,0);

    coef_growth = coef_growth(:);

    u = u+G.phi*coef_growth;
end
