function [model,rho_best,history,cache] = fit_growth_block_ddad( ...
    Xdata,ydata,base_features,base_solution, ...
    centers,directions,center_values, ...
    rho0,lambda,ls_opts,optimizer_opts)
%FIT_GROWTH_BLOCK_DDAD High-level DDAD training of one growth block.
%
% Both PDE-driven and data-driven base solvers can call this same routine.
% The layer-growth scale is ALWAYS trained from solution data.

    model = ...
        prepare_growth_model( ...
            centers,directions,center_values);

    cache = ...
        prepare_growth_ddad_cache( ...
            Xdata,ydata,base_features,base_solution,model);

    [rho_best,history] = ...
        optimize_growth_scale_ddad( ...
            rho0,cache,lambda,ls_opts,optimizer_opts);

    model.rho = rho_best;
end
