function [p0,info] = frequency_initialization_helmholtz(cfg)
    %FREQUENCY_INITIALIZATION_HELMHOLTZ Helmholtz frequency initialization.
    
        problem = struct( ...
            'a1',cfg.a1, ...
            'a2',cfg.a2, ...
            'k',cfg.k);
    
        rhs_fun = @(X) helmholtz_rhs(X,problem);
    
        [p0,info] = ...
            frequency_initialize_gaussian_2d(cfg,rhs_fun);
    
        fprintf( ...
            'Frequency initialization p0 = [%.6f, %.6f]\n', ...
            p0(1),p0(2));
    
        fprintf( ...
            'RHS FFT peak index = [%d, %d]\n', ...
            info.rhs_peak_index(1), ...
            info.rhs_peak_index(2));
    
        fprintf( ...
            'FFT candidates evaluated = %d / %d in %d batches\n', ...
            info.num_fft_candidates, ...
            info.total_candidates, ...
            info.num_batches);
    end