clear;
clear functions;
clc;
close all;

%% ========================================================================
%  Four independent figure windows for the L-shaped Poisson problem
%
%  Figure 1: PDAD solution
%  Figure 2: PDAD + layer growth solution
%  Figure 3: PDAD absolute error
%  Figure 4: PDAD + layer growth absolute error
%
%  The two solution figures use the same color limits.
%  The two error figures use the same color limits.
% =========================================================================


%% ========================================================================
%  Initialize project paths
% =========================================================================

this_file = mfilename('fullpath');

if isempty(this_file)
    error('Please save this script before running it.');
end

this_dir = fileparts(this_file);
addpath(this_dir,'-begin');

[~,project_root] = ...
    config_poisson_lshape_2d('ADAM');


%% ========================================================================
%  User options
% =========================================================================

dense_test_grid = [401,401];

% false:
%     plot |u_h-u|
%
% true:
%     plot log10(|u_h-u|+eps_plot)
use_log_error = false;

eps_plot = 1e-12;

% Save switches
save_figures = true;
save_png = true;
save_pdf = true;
save_eps = true;
save_matlab_fig = true;

% Figure resolution
figure_resolution = 300;


%% ========================================================================
%  Result files
% =========================================================================

result_root = fullfile( ...
    project_root, ...
    'results', ...
    'poisson_lshape_2d');

adam_file = fullfile( ...
    result_root, ...
    'adam', ...
    'poisson_lshape_2d_adam.mat');

growth_file = fullfile( ...
    result_root, ...
    'adam_growth', ...
    'poisson_lshape_2d_adam_growth.mat');


if exist(adam_file,'file') ~= 2

    error( ...
        'Cannot find result file:\n%s', ...
        adam_file);

end

if exist(growth_file,'file') ~= 2

    error( ...
        'Cannot find result file:\n%s', ...
        growth_file);

end


%% ========================================================================
%  Figure output directory
% =========================================================================

figure_dir = fullfile( ...
    result_root, ...
    'paper_figures');

if save_figures && exist(figure_dir,'dir') ~= 7

    [status,message] = mkdir(figure_dir);

    if ~status

        error( ...
            'Failed to create figure directory:\n%s\n%s', ...
            figure_dir, ...
            message);

    end

end


%% ========================================================================
%  Load saved results
% =========================================================================

S_adam = load( ...
    adam_file, ...
    'results');

S_growth = load( ...
    growth_file, ...
    'results');


if ~isfield(S_adam,'results')

    error( ...
        'Variable "results" not found in:\n%s', ...
        adam_file);

end

if ~isfield(S_growth,'results')

    error( ...
        'Variable "results" not found in:\n%s', ...
        growth_file);

end


R_adam = S_adam.results;
R_growth = S_growth.results;


%% ========================================================================
%  Dense reevaluation
% =========================================================================

cfg_eval_adam = R_adam.cfg;
cfg_eval_adam.test_grid = dense_test_grid;
cfg_eval_adam.evaluation_chunk_rows = 500;

cfg_eval_growth = R_growth.cfg;
cfg_eval_growth.test_grid = dense_test_grid;
cfg_eval_growth.evaluation_chunk_rows = 500;


[X_adam,Y_adam,Ue_adam,Up_adam,Err_adam] = ...
    evaluate_and_gridify( ...
        cfg_eval_adam, ...
        R_adam);


[X_growth,Y_growth,Ue_growth,Up_growth,Err_growth] = ...
    evaluate_and_gridify( ...
        cfg_eval_growth, ...
        R_growth);


%% ========================================================================
%  Sanity checks
% =========================================================================

if ~isequal(size(X_adam),size(X_growth)) || ...
        ~isequal(size(Y_adam),size(Y_growth))

    error( ...
        'The PDAD and PDAD+growth evaluation grids do not match.');

end


if any(abs(X_adam(:)-X_growth(:)) > 1e-14) || ...
        any(abs(Y_adam(:)-Y_growth(:)) > 1e-14)

    error( ...
        'The PDAD and PDAD+growth grid coordinates do not match.');

end


exact_difference = ...
    abs(Ue_adam-Ue_growth);

exact_difference = ...
    exact_difference(isfinite(exact_difference));

if ~isempty(exact_difference) && ...
        max(exact_difference) > 1e-12

    warning( ...
        'plotLshape:ExactSolutionMismatch', ...
        ['The exact-solution arrays used for the two methods ', ...
         'are not identical.']);

end


%% ========================================================================
%  Common plotting arrays
% =========================================================================

Xplot = X_adam;
Yplot = Y_adam;


%% ========================================================================
%  Common solution color limits
% =========================================================================

sol_min = min([ ...
    finite_min(Up_adam), ...
    finite_min(Up_growth)]);

sol_max = max([ ...
    finite_max(Up_adam), ...
    finite_max(Up_growth)]);


if ~(isfinite(sol_min) && isfinite(sol_max))
    error('Invalid solution color limits.');
end

if sol_max <= sol_min
    sol_max = sol_min+1;
end


%% ========================================================================
%  Error plotting arrays and common error color limits
% =========================================================================

if use_log_error

    ErrMap_adam = ...
        log10(Err_adam+eps_plot);

    ErrMap_growth = ...
        log10(Err_growth+eps_plot);




else

    ErrMap_adam = ...
        Err_adam;

    ErrMap_growth = ...
        Err_growth;


    err_min = 0;

end





%% ========================================================================
%  Compact independent window positions
%
%  Only the window aspect ratio is changed.
%  Each figure remains an independent MATLAB window.
% =========================================================================

position_1 = [40,530,520,460];
position_2 = [590,530,520,460];
position_3 = [40,40,520,460];
position_4 = [590,40,520,460];


%% ========================================================================
%  Figure 1: PDAD solution
% =========================================================================

fig1 = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',position_1, ...
    'Name','Fixed solution', ...
    'NumberTitle','off', ...
    'InvertHardcopy','off');

layout1 = tiledlayout( ...
    fig1, ...
    1, ...
    1, ...
    'TileSpacing','compact', ...
    'Padding','compact');

ax1 = nexttile(layout1);


plot_field( ...
    ax1, ...
    Xplot, ...
    Yplot, ...
    Up_adam);


axis(ax1,'equal');
axis(ax1,'tight');
box(ax1,'on');

clim(ax1,[sol_min,sol_max]);

colormap(ax1,jet(256));

cb1 = colorbar(ax1);
cb1.LineWidth = 1.0;


hold(ax1,'on');
plot_lshape_boundary(ax1);
hold(ax1,'off');


title( ...
    ax1, ...
    'Fixed solution', ...
    'FontSize',12);

xlabel( ...
    ax1, ...
    '$x$', ...
    'Interpreter','latex', ...
    'FontSize',14);

ylabel( ...
    ax1, ...
    '$y$', ...
    'Interpreter','latex', ...
    'FontSize',14);


set( ...
    ax1, ...
    'FontSize',12, ...
    'LineWidth',1.0, ...
    'Layer','top');
grid(ax1,'off');

set( ...
    ax1, ...
    'XGrid','off', ...
    'YGrid','off', ...
    'ZGrid','off', ...
    'XMinorGrid','off', ...
    'YMinorGrid','off', ...
    'ZMinorGrid','off');

%% ========================================================================
%  Figure 2: PDAD + layer growth solution
% =========================================================================

fig2 = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',position_2, ...
    'Name','PDAD + layer growth solution', ...
    'NumberTitle','off', ...
    'InvertHardcopy','off');

layout2 = tiledlayout( ...
    fig2, ...
    1, ...
    1, ...
    'TileSpacing','compact', ...
    'Padding','compact');

ax2 = nexttile(layout2);


plot_field( ...
    ax2, ...
    Xplot, ...
    Yplot, ...
    Up_growth);


axis(ax2,'equal');
axis(ax2,'tight');
box(ax2,'on');

clim(ax2,[sol_min,sol_max]);

colormap(ax2,jet(256));

cb2 = colorbar(ax2);
cb2.LineWidth = 1.0;


hold(ax2,'on');
plot_lshape_boundary(ax2);
hold(ax2,'off');


title( ...
    ax2, ...
    'PDAD + layer growth solution', ...
    'FontSize',12);

xlabel( ...
    ax2, ...
    '$x$', ...
    'Interpreter','latex', ...
    'FontSize',14);

ylabel( ...
    ax2, ...
    '$y$', ...
    'Interpreter','latex', ...
    'FontSize',14);


set( ...
    ax2, ...
    'FontSize',12, ...
    'LineWidth',1.0, ...
    'Layer','top');
grid(ax2,'off');

set( ...
    ax2, ...
    'XGrid','off', ...
    'YGrid','off', ...
    'ZGrid','off', ...
    'XMinorGrid','off', ...
    'YMinorGrid','off', ...
    'ZMinorGrid','off');

%% ========================================================================
%  Figure 3: PDAD absolute error
% =========================================================================

fig3 = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',position_3, ...
    'Name','Fixed absolute error', ...
    'NumberTitle','off', ...
    'InvertHardcopy','off');

layout3 = tiledlayout( ...
    fig3, ...
    1, ...
    1, ...
    'TileSpacing','compact', ...
    'Padding','compact');

ax3 = nexttile(layout3);


plot_field( ...
    ax3, ...
    Xplot, ...
    Yplot, ...
    ErrMap_adam);


axis(ax3,'equal');
axis(ax3,'tight');
box(ax3,'on');



colormap(ax3,turbo(256));

cb3 = colorbar(ax3);
cb3.LineWidth = 1.0;


hold(ax3,'on');
plot_lshape_boundary(ax3);
hold(ax3,'off');


title( ...
    ax3, ...
    'Fixed absolute error', ...
    'FontSize',12);

xlabel( ...
    ax3, ...
    '$x$', ...
    'Interpreter','latex', ...
    'FontSize',14);

ylabel( ...
    ax3, ...
    '$y$', ...
    'Interpreter','latex', ...
    'FontSize',14);


set( ...
    ax3, ...
    'FontSize',12, ...
    'LineWidth',1.0, ...
    'Layer','top');
grid(ax3,'off');

set( ...
    ax3, ...
    'XGrid','off', ...
    'YGrid','off', ...
    'ZGrid','off', ...
    'XMinorGrid','off', ...
    'YMinorGrid','off', ...
    'ZMinorGrid','off');

%% ========================================================================
%  Figure 4: PDAD + layer growth absolute error
% =========================================================================

fig4 = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',position_4, ...
    'Name','PDAD + layer growth absolute error', ...
    'NumberTitle','off', ...
    'InvertHardcopy','off');

layout4 = tiledlayout( ...
    fig4, ...
    1, ...
    1, ...
    'TileSpacing','compact', ...
    'Padding','compact');

ax4 = nexttile(layout4);


plot_field( ...
    ax4, ...
    Xplot, ...
    Yplot, ...
    ErrMap_growth);


axis(ax4,'equal');
axis(ax4,'tight');
box(ax4,'on');



colormap(ax4,turbo(256));

cb4 = colorbar(ax4);
cb4.LineWidth = 1.0;


hold(ax4,'on');
plot_lshape_boundary(ax4);
hold(ax4,'off');


title( ...
    ax4, ...
    'PDAD + layer growth absolute error', ...
    'FontSize',12);

xlabel( ...
    ax4, ...
    '$x$', ...
    'Interpreter','latex', ...
    'FontSize',14);

ylabel( ...
    ax4, ...
    '$y$', ...
    'Interpreter','latex', ...
    'FontSize',14);


set( ...
    ax4, ...
    'FontSize',12, ...
    'LineWidth',1.0, ...
    'Layer','top');
grid(ax4,'off');

set( ...
    ax4, ...
    'XGrid','off', ...
    'YGrid','off', ...
    'ZGrid','off', ...
    'XMinorGrid','off', ...
    'YMinorGrid','off', ...
    'ZMinorGrid','off');

%% ========================================================================
%  Finish rendering before export
% =========================================================================

drawnow;


%% ========================================================================
%  Save four independent figures
% =========================================================================

if save_figures

    save_one_figure( ...
        fig1, ...
        figure_dir, ...
        'poisson_lshape_pdad_solution', ...
        figure_resolution, ...
        save_png, ...
        save_pdf, ...
        save_eps, ...
        save_matlab_fig);


    save_one_figure( ...
        fig2, ...
        figure_dir, ...
        'poisson_lshape_pdad_growth_solution', ...
        figure_resolution, ...
        save_png, ...
        save_pdf, ...
        save_eps, ...
        save_matlab_fig);


    save_one_figure( ...
        fig3, ...
        figure_dir, ...
        'poisson_lshape_pdad_absolute_error', ...
        figure_resolution, ...
        save_png, ...
        save_pdf, ...
        save_eps, ...
        save_matlab_fig);


    save_one_figure( ...
        fig4, ...
        figure_dir, ...
        'poisson_lshape_pdad_growth_absolute_error', ...
        figure_resolution, ...
        save_png, ...
        save_pdf, ...
        save_eps, ...
        save_matlab_fig);


    fprintf('\n');
    fprintf('Four independent figures saved to:\n%s\n', ...
        figure_dir);

end


%% ========================================================================
%  Local function:
%  Evaluate one method and convert the values to 2-D arrays
% =========================================================================

function [Xgrid,Ygrid,U_exact,U_pred,AbsErr] = ...
    evaluate_and_gridify(cfg_eval,R)

    if isfield(R,'rho_opt')
        rho_opt = R.rho_opt;
    else
        rho_opt = [];
    end


    if isfield(R,'growth_basis')
        growth_basis = R.growth_basis;
    else
        growth_basis = [];
    end


    E = evaluate_poisson_lshape_approximation( ...
        cfg_eval, ...
        R.p_opt, ...
        R.base_basis, ...
        R.coef, ...
        rho_opt, ...
        growth_basis);


    if ~isfield(E,'X') || ...
            ~isfield(E,'u_exact') || ...
            ~isfield(E,'u_pred')

        error( ...
            ['The evaluator output must contain fields ', ...
             '"X", "u_exact", and "u_pred".']);

    end


    X = E.X;

    u_exact_vec = E.u_exact(:);
    u_pred_vec = E.u_pred(:);


    x_unique = unique(X(:,1));
    y_unique = unique(X(:,2));

    nx = numel(x_unique);
    ny = numel(y_unique);


    [Xgrid,Ygrid] = ...
        meshgrid( ...
            x_unique, ...
            y_unique);


    U_exact = nan(ny,nx);
    U_pred = nan(ny,nx);
    AbsErr = nan(ny,nx);


    [~,ix] = ...
        ismember( ...
            X(:,1), ...
            x_unique);

    [~,iy] = ...
        ismember( ...
            X(:,2), ...
            y_unique);


    linear_idx = ...
        sub2ind( ...
            [ny,nx], ...
            iy, ...
            ix);


    U_exact(linear_idx) = ...
        u_exact_vec;

    U_pred(linear_idx) = ...
        u_pred_vec;

    AbsErr(linear_idx) = ...
        abs(u_pred_vec-u_exact_vec);

end


%% ========================================================================
%  Local function:
%  Draw one heatmap
% =========================================================================

function plot_field(ax,X,Y,U)

    surf( ...
        ax, ...
        X, ...
        Y, ...
        zeros(size(U)), ...
        U, ...
        'EdgeColor','none', ...
        'FaceColor','interp');

    view(ax,2);

end


%% ========================================================================
%  Local function:
%  Draw the L-shaped boundary
% =========================================================================

function plot_lshape_boundary(ax)

    xb = [ ...
        -1, ...
         0, ...
         0, ...
         1, ...
         1, ...
        -1, ...
        -1];

    yb = [ ...
        -1, ...
        -1, ...
         0, ...
         0, ...
         1, ...
         1, ...
        -1];


    plot( ...
        ax, ...
        xb, ...
        yb, ...
        'k-', ...
        'LineWidth',1.2);

end


%% ========================================================================
%  Local function:
%  Save one independent figure
% =========================================================================

function save_one_figure( ...
        fig, ...
        output_dir, ...
        file_stem, ...
        resolution, ...
        save_png, ...
        save_pdf, ...
        save_eps, ...
        save_matlab_fig)

    drawnow;

    if save_png

        png_file = fullfile( ...
            output_dir, ...
            [file_stem,'.png']);

        exportgraphics( ...
            fig, ...
            png_file, ...
            'Resolution',resolution, ...
            'BackgroundColor','white');

        fprintf('Saved PNG: %s\n',png_file);

    end


    if save_pdf

        pdf_file = fullfile( ...
            output_dir, ...
            [file_stem,'.pdf']);

        exportgraphics( ...
            fig, ...
            pdf_file, ...
            'ContentType','vector', ...
            'BackgroundColor','white');

        fprintf('Saved PDF: %s\n',pdf_file);

    end


    if save_eps

        eps_file = fullfile( ...
            output_dir, ...
            [file_stem,'.eps']);

        set( ...
            fig, ...
            'Renderer','painters', ...
            'PaperPositionMode','auto');

        print( ...
            fig, ...
            eps_file, ...
            '-depsc', ...
            '-painters');

        fprintf('Saved EPS: %s\n',eps_file);

    end


    if save_matlab_fig

        fig_file = fullfile( ...
            output_dir, ...
            [file_stem,'.fig']);

        savefig(fig,fig_file);

        fprintf('Saved FIG: %s\n',fig_file);

    end

end


%% ========================================================================
%  Local function:
%  Minimum over finite entries
% =========================================================================

function value = finite_min(A)

    values = A(isfinite(A));

    if isempty(values)
        value = NaN;
    else
        value = min(values);
    end

end


%% ========================================================================
%  Local function:
%  Maximum over finite entries
% =========================================================================

function value = finite_max(A)

    values = A(isfinite(A));

    if isempty(values)
        value = NaN;
    else
        value = max(values);
    end

end