function [r0,info] = frequency_initialization(cfg)
    %FREQUENCY_INITIALIZATION Poisson Gaussian frequency initialization.
    %
    % The common engine preserves the established candidate set, feasibility
    % test, batched FFT, exact early stopping, and minimum-norm tie-breaking.
    % This problem-dependent wrapper supplies only the Poisson right-hand side.
    
        [r0,info] = ...
            frequency_initialize_gaussian_2d(cfg,@rhs);
    
        fprintf( ...
            'Frequency initialization r = (%.6f, %.6f)\n', ...
            r0(1),r0(2));
    
        fprintf( ...
            'Frequency FFT candidates = %d / %d, batches = %d\n', ...
            info.num_fft_candidates, ...
            info.total_candidates, ...
            info.num_batches);
    end
    